# Generated by Django 5.2.4 on 2025-08-04 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactmessage_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclegalleryimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app.vehicle'),
        ),
    ]
